### ISSUE TITLE
To C, or not to C, that is the question

### ISSUE THREAD

**Issue by IvanUkhov** [stainless-steel/blas-sys#10]
Now that I have happily removed the C interface, I have a suspicion that it was a mistake: that was the interface that should have stayed, and the Fortran one should have gone. It seems that, when calling Fortran routines, all the optimization done by the OpenBLAS developers is completely ignored. The package is basically hitting the [reference](https://github.com/xianyi/OpenBLAS/tree/develop/reference) implementation by Netlib. The optimized routines can be accessed only via the C interface. I do not think that the package is currently reaching, for instance, any of [these](https://github.com/xianyi/OpenBLAS/tree/develop/kernel/x86_64) low-level implementations.

However, I am not 100% sure, and an opinion of an OpenBLAS expert is highly needed.

// ping @cmr

Regards,
Ivan

**Comment by IvanUkhov** [comment]
@xianyi, which interface should one use in order to get the most out of OpenBLAS? For instance, when doing matrix-matrix multiplication, should one call `dgemm_`, `cblas_gemm`, or something else? Thanks!

**Comment by cmr** [comment]
Oh, weird. I wasn't aware of this issue. I assumed the interfaces were pretty much the same, but with CBLAS having an extra call to the Fortran.

**Comment by IvanUkhov** [comment]
As I said, these are just my speculations; I don’t know what is the actual case. For example, [here](http://stackoverflow.com/questions/1303182/how-does-blas-get-such-extreme-performance#answer-11421344) there is the following claim:

> By the way, most (or even all) of the high performance BLAS implementations are NOT implemented in Fortran. ATLAS is implemented in C. GotoBLAS/OpenBLAS is implemented in C and its performance critical parts in Assembler. Only the reference implementation of BLAS is implemented in Fortran. However, **all these BLAS implementations provide a Fortran interface such that it can be linked against LAPACK (LAPACK gains all its performance from BLAS)**.

So maybe the package does reach the optimized routines written in C or assembly. But then Fortran wraps around C, not the other way around.

**Comment by xianyi** [comment]
OpenBLAS is implemented in C and assembly codes. We used C to provide Fortran interface. For example, `DGEMM` in Fortran, we implemented `dgemm_` in C codes.

Thus, the `dgemm_` and `cblas_dgemm` should provide the same performance.

**Comment by IvanUkhov** [comment]
@xianyi, thanks! Such a relieve)
