### ISSUE TITLE
Use #![no_std] for the next major version?

### ISSUE THREAD

**Issue by bluss** [stainless-steel/blas-sys#16]
Every crate that can should be no_std, isn't it so? It may not have impact in practice just yet.

**Comment by IvanUkhov** [comment]
Thanks! Yeah, the standard library is an excess here. Eliminating it is surely a good idea, and it [doesn’t seem](https://travis-ci.org/stainless-steel/blas-sys/builds/122581049) to be causing any problems on any of the channels. To be honest, I was under the impression that the compiler was smart enough to exclude what was not really needed.

By the way, I’ve sent you an invitation to a group whose members have write permissions on BLAS/LAPACK-related crates. So you can make any changes that you think are necessary on your own; I totally trust your judgement.

**Comment by bluss** [comment]
Thank you for the confidence in me.

We need to turn off the std feature in libc as well. (I guess it exists mainly for backwards compatibility.) no_std will set the requirement to Rust 1.6.

**Comment by bluss** [comment]
We will have to see how this goes, I will try to make a no-std app using blis-sys. Maybe we need to put no_std into all the crates in the network (including the blas providers)?

**Comment by IvanUkhov** [comment]
Indeed, everything depends on `libc`. OK, I’ll then take care of sprinkling `no_std` over all the crates in the network.

**Comment by bluss** [comment]
Like you said, it doesn't quite feel right to have to manually say it per crate.
