### ISSUE TITLE
Function / Module Documentation

### ISSUE THREAD

**Issue by masonium** [stainless-steel/blas-sys#18]
Is there any desire for documentation within blas-sys? There are references sheets for BLAS generally, but it would certainly be more convenient for the crate's documentation to have enough information within itself. At the very least, each function could have a brief stub and link to the relevant netlib or Intel MKL docs. 

I'd be happy to contribute some documentation if there is a template for doing so. (I'm also happy to come up with a template subject to approval.)

**Comment by IvanUkhov** [comment]
I have no objections in general. However, it sounds like a ton of tedious work unless one writes a script for pulling the documentation from some trustworthy source such as [Netlib](http://www.netlib.org/lapack/explore-html/). Having such a script, one can also easily make adjustments to the template you mention. Another question is: what is the most appropriate place for this documentation? There is a higher-level crate called [`blas`](https://crates.io/crates/blas).

**Comment by masonium** [comment]
Good point. The blas crate is probably a better place for it, since it's more geared for end-usage.

**Comment by IvanUkhov** [comment]
Note, however, that everything in `blas/src` is generated by the scripts in `blas/bin`. It’s important to preserve this for future updates.
