### ISSUE TITLE
Should there be a default provider?

### ISSUE THREAD

**Issue by cmr** [stainless-steel/blas-sys#5]
Cargo has no way to force only one of a given set of features to be present. If you use netlib, you need to be sure to opt out of the default features otherwise there will be a double-define of `raw`.

**Comment by cmr** [comment]
Alternatively, we could add `#[cfg(not(feature = "openblas"))]` to the other `extern crates`, but that scales very poorly...

**Comment by cmr** [comment]
Actually no it doesn't, that's a good solution.

**Comment by IvanUkhov** [comment]
I’ve also ran into the same problem. I have to do

```
features = ["netlib"]
default = false
```

to exclude OpenBLAS and switch to Netlib.

**Comment by IvanUkhov** [comment]
But then, in one provider, one will have to mention all other providers, which, as you said, does not really scale that well.

**Comment by IvanUkhov** [comment]
Not having a default provider might be a better option. We just need to make sure to have clear installation instructions.

**Comment by cmr** [comment]
You don't actually have to mention all other providers (I thought this too at first), you only need to mention the default provider. Setting more than one provider will still break, but, well, that can't really be well-defined at all.

**Comment by IvanUkhov** [comment]
Hmm, yes, indeed.

**Comment by IvanUkhov** [comment]
@cmr, it turns out that one cannot disable the default features of `libblas-sys` and `liblapack-sys` from a package that uses `blas` or `lapack`. It ends up compiling both `openblas-provider` and `netlib-provider`. I tried it from [`matrix`](https://github.com/stainless-steel/matrix). No luck.

**Comment by cmr** [comment]
@IvanUkhov How annoying... oh well :( I'm not sure it will be possible to chose an implementation, then, because *every* user would have to chose the feature, even libraries that would like to leave the choice up to an application.

**Comment by IvanUkhov** [comment]
Yeah, that’s very unfortunate. I hope that, some day, Cargo will be able to handle such cases. For now a sensible solution could be to eliminate defaults and reexport the provider features in all packages that depend on `libblas-sys` and `liblapack-sys`. The final application will have to consciously take the final decision regarding which provider to use.

**Comment by IvanUkhov** [comment]
It’s going to be really annoying to mention this requirement in the description of every package, and it’s not that scalable with the number of providers.

**Comment by bluss** [comment]
Cargo features are unfortunately designed to be additive, they will union automatically. So features that exclude each other don't really work.

**Comment by IvanUkhov** [comment]
@bluss, thanks for the feedback! Would you say that what we have right now (feature reexporting) is a sensible solution in the state of affairs?

**Comment by IvanUkhov** [comment]
Closed in favor of #17.
